#############################################################################
# Makefile for building: vomit
# Generated by qmake (2.01a) (Qt 4.5.1) on: Thu Jun 18 21:13:04 2009
# Project:  vomit.pro
# Template: app
# Command: /home/kling/src/qt-copy/bin/qmake -unix -o Makefile vomit.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DVM_NOPFQ -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../qt-copy/mkspecs/linux-g++-64 -I. -I../../qt-copy/include/QtCore -I../../qt-copy/include/QtGui -I../../qt-copy/include -I. -I. -Iinclude -Idisasm/include -Igui -Ihw -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/home/kling/src/qt-copy/lib
LIBS          = $(SUBLIBS)  -L/home/kling/src/qt-copy/lib -lQtGui -L/home/kling/src/qt-copy/lib -L/usr/X11R6/lib64 -pthread -lpng -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/kling/src/qt-copy/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = 186.cpp \
		config.cpp \
		debug.cpp \
		dump.cpp \
		fpu.cpp \
		vmcalls.cpp \
		vomit.cpp \
		8086/bcd.cpp \
		8086/bitwise.cpp \
		8086/cpu.cpp \
		8086/flags.cpp \
		8086/interrupt.cpp \
		8086/io.cpp \
		8086/jump.cpp \
		8086/loop.cpp \
		8086/math.cpp \
		8086/memory.cpp \
		8086/misc.cpp \
		8086/modrm.cpp \
		8086/mov.cpp \
		8086/stack.cpp \
		8086/string.cpp \
		8086/wrap.cpp \
		bios/floppy.cpp \
		bios/video.cpp \
		disasm/disasm.cpp \
		disasm/disasm_modrm.cpp \
		disasm/tables.cpp \
		gui/codeview.cpp \
		gui/console.cpp \
		gui/cpuview.cpp \
		gui/hexspinbox.cpp \
		gui/main.cpp \
		gui/mainwindow.cpp \
		gui/memview.cpp \
		gui/screen.cpp \
		gui/worker.cpp \
		hw/busmouse.cpp \
		hw/dma.cpp \
		hw/fdc.cpp \
		hw/gameport.cpp \
		hw/ide.cpp \
		hw/keyboard.cpp \
		hw/pic.cpp \
		hw/pit.cpp \
		hw/vga.cpp \
		hw/vomctl.cpp \
		hw/iodevice.cpp moc_codeview.cpp \
		moc_console.cpp \
		moc_cpuview.cpp \
		moc_hexspinbox.cpp \
		moc_mainwindow.cpp \
		moc_memview.cpp \
		moc_screen.cpp \
		moc_worker.cpp
OBJECTS       = 186.o \
		config.o \
		debug.o \
		dump.o \
		fpu.o \
		vmcalls.o \
		vomit.o \
		bcd.o \
		bitwise.o \
		cpu.o \
		flags.o \
		interrupt.o \
		io.o \
		jump.o \
		loop.o \
		math.o \
		memory.o \
		misc.o \
		modrm.o \
		mov.o \
		stack.o \
		string.o \
		wrap.o \
		floppy.o \
		video.o \
		disasm.o \
		disasm_modrm.o \
		tables.o \
		codeview.o \
		console.o \
		cpuview.o \
		hexspinbox.o \
		main.o \
		mainwindow.o \
		memview.o \
		screen.o \
		worker.o \
		busmouse.o \
		dma.o \
		fdc.o \
		gameport.o \
		ide.o \
		keyboard.o \
		pic.o \
		pit.o \
		vga.o \
		vomctl.o \
		iodevice.o \
		moc_codeview.o \
		moc_console.o \
		moc_cpuview.o \
		moc_hexspinbox.o \
		moc_mainwindow.o \
		moc_memview.o \
		moc_screen.o \
		moc_worker.o
DIST          = ../../qt-copy/mkspecs/common/g++.conf \
		../../qt-copy/mkspecs/common/unix.conf \
		../../qt-copy/mkspecs/common/linux.conf \
		../../qt-copy/mkspecs/qconfig.pri \
		../../qt-copy/mkspecs/features/qt_functions.prf \
		../../qt-copy/mkspecs/features/qt_config.prf \
		../../qt-copy/mkspecs/features/exclusive_builds.prf \
		../../qt-copy/mkspecs/features/default_pre.prf \
		../../qt-copy/mkspecs/features/debug.prf \
		../../qt-copy/mkspecs/features/default_post.prf \
		../../qt-copy/mkspecs/features/warn_on.prf \
		../../qt-copy/mkspecs/features/qt.prf \
		../../qt-copy/mkspecs/features/unix/thread.prf \
		../../qt-copy/mkspecs/features/moc.prf \
		../../qt-copy/mkspecs/features/resources.prf \
		../../qt-copy/mkspecs/features/uic.prf \
		../../qt-copy/mkspecs/features/yacc.prf \
		../../qt-copy/mkspecs/features/lex.prf \
		../../qt-copy/mkspecs/features/include_source_dir.prf \
		vomit.pro
QMAKE_TARGET  = vomit
DESTDIR       = 
TARGET        = vomit

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: vomit.pro  ../../qt-copy/mkspecs/linux-g++-64/qmake.conf ../../qt-copy/mkspecs/common/g++.conf \
		../../qt-copy/mkspecs/common/unix.conf \
		../../qt-copy/mkspecs/common/linux.conf \
		../../qt-copy/mkspecs/qconfig.pri \
		../../qt-copy/mkspecs/features/qt_functions.prf \
		../../qt-copy/mkspecs/features/qt_config.prf \
		../../qt-copy/mkspecs/features/exclusive_builds.prf \
		../../qt-copy/mkspecs/features/default_pre.prf \
		../../qt-copy/mkspecs/features/debug.prf \
		../../qt-copy/mkspecs/features/default_post.prf \
		../../qt-copy/mkspecs/features/warn_on.prf \
		../../qt-copy/mkspecs/features/qt.prf \
		../../qt-copy/mkspecs/features/unix/thread.prf \
		../../qt-copy/mkspecs/features/moc.prf \
		../../qt-copy/mkspecs/features/resources.prf \
		../../qt-copy/mkspecs/features/uic.prf \
		../../qt-copy/mkspecs/features/yacc.prf \
		../../qt-copy/mkspecs/features/lex.prf \
		../../qt-copy/mkspecs/features/include_source_dir.prf \
		/home/kling/src/qt-copy/lib/libQtGui.prl \
		/home/kling/src/qt-copy/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile vomit.pro
../../qt-copy/mkspecs/common/g++.conf:
../../qt-copy/mkspecs/common/unix.conf:
../../qt-copy/mkspecs/common/linux.conf:
../../qt-copy/mkspecs/qconfig.pri:
../../qt-copy/mkspecs/features/qt_functions.prf:
../../qt-copy/mkspecs/features/qt_config.prf:
../../qt-copy/mkspecs/features/exclusive_builds.prf:
../../qt-copy/mkspecs/features/default_pre.prf:
../../qt-copy/mkspecs/features/debug.prf:
../../qt-copy/mkspecs/features/default_post.prf:
../../qt-copy/mkspecs/features/warn_on.prf:
../../qt-copy/mkspecs/features/qt.prf:
../../qt-copy/mkspecs/features/unix/thread.prf:
../../qt-copy/mkspecs/features/moc.prf:
../../qt-copy/mkspecs/features/resources.prf:
../../qt-copy/mkspecs/features/uic.prf:
../../qt-copy/mkspecs/features/yacc.prf:
../../qt-copy/mkspecs/features/lex.prf:
../../qt-copy/mkspecs/features/include_source_dir.prf:
/home/kling/src/qt-copy/lib/libQtGui.prl:
/home/kling/src/qt-copy/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile vomit.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/vomit1.0.0 || $(MKDIR) .tmp/vomit1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/vomit1.0.0/ && $(COPY_FILE) --parents gui/codeview.h gui/console.h gui/cpuview.h gui/hexspinbox.h gui/mainwindow.h gui/memview.h gui/screen.h gui/worker.h hw/iodevice.h hw/vomctl.h include/186.h include/8086.h include/debug.h include/floppy.h include/templates.h include/vga.h include/vomit.h disasm/include/disasm.h disasm/include/insn-types.h .tmp/vomit1.0.0/ && $(COPY_FILE) --parents 186.cpp config.cpp debug.cpp dump.cpp fpu.cpp vmcalls.cpp vomit.cpp 8086/bcd.cpp 8086/bitwise.cpp 8086/cpu.cpp 8086/flags.cpp 8086/interrupt.cpp 8086/io.cpp 8086/jump.cpp 8086/loop.cpp 8086/math.cpp 8086/memory.cpp 8086/misc.cpp 8086/modrm.cpp 8086/mov.cpp 8086/stack.cpp 8086/string.cpp 8086/wrap.cpp bios/floppy.cpp bios/video.cpp disasm/disasm.cpp disasm/disasm_modrm.cpp disasm/tables.cpp gui/codeview.cpp gui/console.cpp gui/cpuview.cpp gui/hexspinbox.cpp gui/main.cpp gui/mainwindow.cpp gui/memview.cpp gui/screen.cpp gui/worker.cpp hw/busmouse.cpp hw/dma.cpp hw/fdc.cpp hw/gameport.cpp hw/ide.cpp hw/keyboard.cpp hw/pic.cpp hw/pit.cpp hw/vga.cpp hw/vomctl.cpp hw/iodevice.cpp .tmp/vomit1.0.0/ && (cd `dirname .tmp/vomit1.0.0` && $(TAR) vomit1.0.0.tar vomit1.0.0 && $(COMPRESS) vomit1.0.0.tar) && $(MOVE) `dirname .tmp/vomit1.0.0`/vomit1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/vomit1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_codeview.cpp moc_console.cpp moc_cpuview.cpp moc_hexspinbox.cpp moc_mainwindow.cpp moc_memview.cpp moc_screen.cpp moc_worker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_codeview.cpp moc_console.cpp moc_cpuview.cpp moc_hexspinbox.cpp moc_mainwindow.cpp moc_memview.cpp moc_screen.cpp moc_worker.cpp
moc_codeview.cpp: gui/codeview.h
	/home/kling/src/qt-copy/bin/moc $(DEFINES) $(INCPATH) gui/codeview.h -o moc_codeview.cpp

moc_console.cpp: gui/console.h
	/home/kling/src/qt-copy/bin/moc $(DEFINES) $(INCPATH) gui/console.h -o moc_console.cpp

moc_cpuview.cpp: gui/cpuview.h
	/home/kling/src/qt-copy/bin/moc $(DEFINES) $(INCPATH) gui/cpuview.h -o moc_cpuview.cpp

moc_hexspinbox.cpp: gui/hexspinbox.h
	/home/kling/src/qt-copy/bin/moc $(DEFINES) $(INCPATH) gui/hexspinbox.h -o moc_hexspinbox.cpp

moc_mainwindow.cpp: gui/mainwindow.h
	/home/kling/src/qt-copy/bin/moc $(DEFINES) $(INCPATH) gui/mainwindow.h -o moc_mainwindow.cpp

moc_memview.cpp: gui/memview.h
	/home/kling/src/qt-copy/bin/moc $(DEFINES) $(INCPATH) gui/memview.h -o moc_memview.cpp

moc_screen.cpp: include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		gui/screen.h
	/home/kling/src/qt-copy/bin/moc $(DEFINES) $(INCPATH) gui/screen.h -o moc_screen.cpp

moc_worker.cpp: gui/worker.h
	/home/kling/src/qt-copy/bin/moc $(DEFINES) $(INCPATH) gui/worker.h -o moc_worker.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

186.o: 186.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o 186.o 186.cpp

config.o: config.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config.o config.cpp

debug.o: debug.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		disasm/include/disasm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug.o debug.cpp

dump.o: dump.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h \
		disasm/include/disasm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dump.o dump.cpp

fpu.o: fpu.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fpu.o fpu.cpp

vmcalls.o: vmcalls.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vmcalls.o vmcalls.cpp

vomit.o: vomit.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vomit.o vomit.cpp

bcd.o: 8086/bcd.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bcd.o 8086/bcd.cpp

bitwise.o: 8086/bitwise.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/templates.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bitwise.o 8086/bitwise.cpp

cpu.o: 8086/cpu.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cpu.o 8086/cpu.cpp

flags.o: 8086/flags.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flags.o 8086/flags.cpp

interrupt.o: 8086/interrupt.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interrupt.o 8086/interrupt.cpp

io.o: 8086/io.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o io.o 8086/io.cpp

jump.o: 8086/jump.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jump.o 8086/jump.cpp

loop.o: 8086/loop.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loop.o 8086/loop.cpp

math.o: 8086/math.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/templates.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o math.o 8086/math.cpp

memory.o: 8086/memory.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o memory.o 8086/memory.cpp

misc.o: 8086/misc.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o misc.o 8086/misc.cpp

modrm.o: 8086/modrm.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modrm.o 8086/modrm.cpp

mov.o: 8086/mov.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mov.o 8086/mov.cpp

stack.o: 8086/stack.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stack.o 8086/stack.cpp

string.o: 8086/string.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o string.o 8086/string.cpp

wrap.o: 8086/wrap.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wrap.o 8086/wrap.cpp

floppy.o: bios/floppy.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o floppy.o bios/floppy.cpp

video.o: bios/video.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video.o bios/video.cpp

disasm.o: disasm/disasm.cpp disasm/include/insn-types.h \
		disasm/include/disasm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o disasm.o disasm/disasm.cpp

disasm_modrm.o: disasm/disasm_modrm.cpp disasm/include/insn-types.h \
		disasm/include/disasm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o disasm_modrm.o disasm/disasm_modrm.cpp

tables.o: disasm/tables.cpp disasm/include/insn-types.h \
		disasm/include/disasm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tables.o disasm/tables.cpp

codeview.o: gui/codeview.cpp gui/codeview.h \
		include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		disasm/include/disasm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o codeview.o gui/codeview.cpp

console.o: gui/console.cpp gui/console.h \
		include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		disasm/include/disasm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o console.o gui/console.cpp

cpuview.o: gui/cpuview.cpp gui/cpuview.h \
		include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		disasm/include/disasm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cpuview.o gui/cpuview.cpp

hexspinbox.o: gui/hexspinbox.cpp gui/hexspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hexspinbox.o gui/hexspinbox.cpp

main.o: gui/main.cpp gui/mainwindow.h \
		gui/screen.h \
		include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o gui/main.cpp

mainwindow.o: gui/mainwindow.cpp gui/mainwindow.h \
		gui/worker.h \
		gui/console.h \
		gui/screen.h \
		include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		gui/memview.h \
		gui/codeview.h \
		gui/hexspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o gui/mainwindow.cpp

memview.o: gui/memview.cpp gui/memview.h \
		include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o memview.o gui/memview.cpp

screen.o: gui/screen.cpp gui/screen.h \
		include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o screen.o gui/screen.cpp

worker.o: gui/worker.cpp gui/worker.h \
		include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o worker.o gui/worker.cpp

busmouse.o: hw/busmouse.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o busmouse.o hw/busmouse.cpp

dma.o: hw/dma.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dma.o hw/dma.cpp

fdc.o: hw/fdc.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fdc.o hw/fdc.cpp

gameport.o: hw/gameport.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameport.o hw/gameport.cpp

ide.o: hw/ide.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ide.o hw/ide.cpp

keyboard.o: hw/keyboard.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyboard.o hw/keyboard.cpp

pic.o: hw/pic.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pic.o hw/pic.cpp

pit.o: hw/pit.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pit.o hw/pit.cpp

vga.o: hw/vga.cpp include/vomit.h \
		include/8086.h \
		include/186.h \
		include/floppy.h \
		include/vga.h \
		include/debug.h \
		disasm/include/disasm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vga.o hw/vga.cpp

vomctl.o: hw/vomctl.cpp hw/vomctl.h \
		hw/iodevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vomctl.o hw/vomctl.cpp

iodevice.o: hw/iodevice.cpp hw/iodevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iodevice.o hw/iodevice.cpp

moc_codeview.o: moc_codeview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_codeview.o moc_codeview.cpp

moc_console.o: moc_console.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_console.o moc_console.cpp

moc_cpuview.o: moc_cpuview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cpuview.o moc_cpuview.cpp

moc_hexspinbox.o: moc_hexspinbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hexspinbox.o moc_hexspinbox.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_memview.o: moc_memview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_memview.o moc_memview.cpp

moc_screen.o: moc_screen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_screen.o moc_screen.cpp

moc_worker.o: moc_worker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_worker.o moc_worker.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

